satellite_url: "https://satellite.local"
satellite_user: "admin"
satellite_password: "123456"

organization: "Linsoft"
location: "Tunis"
hostgroup: "RHEL9-Group"
compute_resource: "KVM-local"
root_pass: "12345678"
openscap_capsule: "satellite.local"
subnet: "satellite-network"
domain: "local"

prometheus_server: "192.168.122.247"  
node_exporter_version: "1.8.1"

ssh_permit_root_login: "no"
ssh_password_auth: "no"
