---
- name: Remediate VM
  hosts: all
  become: true
  tasks:
    - name: Restart all failed services
      shell: |
        systemctl list-units --state=failed --no-legend | awk '{print $1}' | xargs -r systemctl restart
      ignore_errors: true

    - name: Ensure critical services are running
      service:
        name: "{{ item }}"
        state: started
      loop:
        - sshd
        - chronyd
      ignore_errors: true
